#  Creating a numpy array

In [1]:
import numpy as np

In [2]:
data = [1, 2.5, 3.1, 4, 5.6]

In [3]:
arr = np.array(data)

In [4]:
arr

array([1. , 2.5, 3.1, 4. , 5.6])

In [5]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
arr = np.array(data)

In [7]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# NUMBER OF DIMENSIONS

In [8]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr.ndim

2

# SHAPE OF AN ARRAY

In [10]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr.shape

(2, 4)

# SIZE OF AN ARRAY

In [12]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr.size

8

# RESHAPING AN ARRAY


In [14]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
arr.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# FLATTENING AN ARRAY


In [17]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

# DATA TYPE 

In [19]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr.dtype

dtype('int32')

Boolean

In [21]:
array = np.array([True, False, True], dtype=bool)

In [22]:
array

array([ True, False,  True])

String

In [24]:
array = np.array(['hello', 'world', 'numpy'], dtype=np.string_)

In [25]:
array

array([b'hello', b'world', b'numpy'], dtype='|S5')

Unicode

In [27]:
array = np.array([u'سلام',u'بله',u'خیر'], dtype=np.unicode_)

In [28]:
array

array(['سلام', 'بله', 'خیر'], dtype='<U4')

Object

In [30]:
array = np.array([{"name": "John", "age": 25}, [1, 2, 3], "hello"], dtype=object)

In [31]:
array

array([{'name': 'John', 'age': 25}, list([1, 2, 3]), 'hello'],
      dtype=object)

# CASTING DATA TYPE

In [32]:
array = np.array([1, 2, 3, 4, 5])

In [33]:
array

array([1, 2, 3, 4, 5])

In [34]:
array.astype(np.float64)

array([1., 2., 3., 4., 5.])

# ARRAY CREATION FUNCTIONS

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
np.empty((1,2))

array([[-1.54594165e-019, -6.73651809e-102]])

In [38]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.zeros_like(array)

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
np.ones_like(array)

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [43]:
np.full((2, 2), np.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [46]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
np.linspace(0,10,5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [48]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [49]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.random.rand(2, 3)

array([[0.53194789, 0.34947592, 0.83267288],
       [0.80052041, 0.57181098, 0.41183668]])