#  Creating a numpy array

In [1]:
import numpy as np

In [2]:
data = [1, 2.5, 3.1, 4, 5.6]

In [3]:
arr = np.array(data)

In [4]:
arr

array([1. , 2.5, 3.1, 4. , 5.6])

In [5]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
arr = np.array(data)

In [7]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# NUMBER OF DIMENSIONS

In [8]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr.ndim

2

# SHAPE OF AN ARRAY

In [10]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr.shape

(2, 4)

# SIZE OF AN ARRAY

In [12]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr.size

8

# RESHAPING AN ARRAY


In [14]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
arr.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# FLATTENING AN ARRAY


In [17]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

# DATA TYPE 

In [19]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr.dtype

dtype('int32')

Boolean

In [21]:
array = np.array([True, False, True], dtype=bool)

In [22]:
array

array([ True, False,  True])

String

In [23]:
array = np.array(['hello', 'world', 'numpy'], dtype=np.string_)

In [24]:
array

array([b'hello', b'world', b'numpy'], dtype='|S5')

Unicode

In [25]:
array = np.array([u'سلام',u'بله',u'خیر'], dtype=np.unicode_)

In [26]:
array

array(['سلام', 'بله', 'خیر'], dtype='<U4')

Object

In [27]:
array = np.array([{"name": "John", "age": 25}, [1, 2, 3], "hello"], dtype=object)

In [28]:
array

array([{'name': 'John', 'age': 25}, list([1, 2, 3]), 'hello'],
      dtype=object)

# CASTING DATA TYPE

In [29]:
array = np.array([1, 2, 3, 4, 5])

In [30]:
array

array([1, 2, 3, 4, 5])

In [31]:
array.astype(np.float64)

array([1., 2., 3., 4., 5.])

# ARRAY CREATION FUNCTIONS

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [34]:
np.empty((1,2))

array([[1.92270724e+152, 3.69346744e-182]])

In [35]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [36]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.zeros_like(array)

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
np.ones_like(array)

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [40]:
np.full((2, 2), np.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
np.linspace(0,10,5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [45]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [46]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.random.rand(2, 3)

array([[0.4859202 , 0.39857192, 0.09224104],
       [0.9350048 , 0.35655832, 0.13207801]])

# NAN AND INFINITY


In [48]:
array = np.array([1, 2, np.nan, 3, 4, np.inf])

In [49]:
array

array([ 1.,  2., nan,  3.,  4., inf])

In [50]:
np.isnan(array)

array([False, False,  True, False, False, False])

In [51]:
np.isinf(array)

array([False, False, False, False, False,  True])

# ARITHMETIC OPERATIONS 

In [52]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([5,4,3,2,1])

In [53]:
array1

array([1, 2, 3, 4, 5])

In [54]:
array2

array([5, 4, 3, 2, 1])

In [55]:
array1 - array2

array([-4, -2,  0,  2,  4])

In [56]:
array1 * array2

array([5, 8, 9, 8, 5])

In [57]:
1 / array1

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [58]:
array1 ** 2  

array([ 1,  4,  9, 16, 25])

In [59]:
array1>array2

array([False, False, False,  True,  True])

In [60]:
array1 == array2

array([False, False,  True, False, False])

# BROADCASTING RULE


In [61]:
array1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
array2 = np.array([1, 2, 3])

In [62]:
array1 + array2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [63]:
array1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]])
array2 = np.array([1, 2])

In [64]:
#array1 + array2

# INTEGER INDEXING

In [65]:
array = np.array([1, 2, 3, 4])

In [66]:
print(array[0])

1


In [67]:
print(array[[0, 2]])

[1 3]


In [68]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
print(array[0, 0])

1


In [70]:
print(array[[0, 1], [0, 1]])

[1 4]


In [71]:
array[0, 0] = 10
print(array)

[[10  2]
 [ 3  4]
 [ 5  6]]


# SLICING

In [72]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
print(array[:5])

[1 2 3 4 5]


In [74]:
print(array[2:5])

[3 4 5]


In [75]:
print(array[2:])

[3 4 5 6 7 8 9]


In [76]:
print(array[1:5:2])

[2 4]


In [77]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
print(array[-5:-1])

[5 6 7 8]


In [79]:
print(array[-5:])

[5 6 7 8 9]


In [80]:
print(array[:-5])

[1 2 3 4]


In [81]:
print(array[-5:-1 :2])

[5 7]


In [82]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
arr_slice = array [5:8]

In [84]:
arr_slice

array([5, 6, 7])

In [85]:
arr_slice[:] = 752 

In [86]:
arr_slice

array([752, 752, 752])

In [87]:
array

array([  0,   1,   2,   3,   4, 752, 752, 752,   8,   9])

# BOOLEAN INDEXING

In [88]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [89]:
print(names == 'Bob')

[ True False False  True False False False]


In [90]:
print(data)

[[-1.51176611  0.36497303 -0.01197355 -1.26714677]
 [-0.44780336  0.46393284 -0.32227261  0.41303121]
 [-1.46967885  0.83050907  1.00669703  1.09282531]
 [-0.10321262  0.41567444  1.4354883   1.73004908]
 [ 0.13437433  0.34322846  0.22862588 -0.31078306]
 [-0.54434924 -1.09368098 -0.04431421  0.13284746]
 [-0.47052958  0.71667352  1.86855184  1.02746099]]


In [91]:
print(data[names == 'Bob'])

[[-1.51176611  0.36497303 -0.01197355 -1.26714677]
 [-0.10321262  0.41567444  1.4354883   1.73004908]]


In [92]:
print(names != 'Bob')

[False  True  True False  True  True  True]


In [93]:
print(data[names != 'Bob'])

[[-0.44780336  0.46393284 -0.32227261  0.41303121]
 [-1.46967885  0.83050907  1.00669703  1.09282531]
 [ 0.13437433  0.34322846  0.22862588 -0.31078306]
 [-0.54434924 -1.09368098 -0.04431421  0.13284746]
 [-0.47052958  0.71667352  1.86855184  1.02746099]]


In [94]:
mask = (names == 'Bob') | (names == 'will')
mask

array([ True, False, False,  True, False, False, False])

In [95]:
data[mask]

array([[-1.51176611,  0.36497303, -0.01197355, -1.26714677],
       [-0.10321262,  0.41567444,  1.4354883 ,  1.73004908]])

In [96]:
data[data<0]=0

In [97]:
data

array([[0.        , 0.36497303, 0.        , 0.        ],
       [0.        , 0.46393284, 0.        , 0.41303121],
       [0.        , 0.83050907, 1.00669703, 1.09282531],
       [0.        , 0.41567444, 1.4354883 , 1.73004908],
       [0.13437433, 0.34322846, 0.22862588, 0.        ],
       [0.        , 0.        , 0.        , 0.13284746],
       [0.        , 0.71667352, 1.86855184, 1.02746099]])

# CONDITIONAL LOGIC

In [98]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

In [99]:
np.where(x>3 , x, y)

array([6, 7, 8, 4, 5])

# UNIVERSAL FUNCTIONS

In [100]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [101]:
np.sqrt(array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
       27.4226184 , 27.4226184 , 27.4226184 ,  2.82842712,  3.        ])

In [102]:
np.exp(array)

C:\Users\IDEH\AppData\Local\Temp\ipykernel_13604\3993411681.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(array)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01,            inf,            inf,            inf,
       2.98095799e+03, 8.10308393e+03])

In [103]:
np.square(array)

array([     0,      1,      4,      9,     16, 565504, 565504, 565504,
           64,     81])

In [104]:
array1 = np.random.randn(4)
array2 = np.random.randn(4)

In [105]:
array1

array([ 1.7534491 , -0.14772057,  0.32371441,  1.43004325])

In [106]:
array2

array([-0.23901099, -0.34707477,  0.30687437,  0.34096855])

In [107]:
np.maximum(array1,array2)

array([ 1.7534491 , -0.14772057,  0.32371441,  1.43004325])

In [108]:
np.minimum(array1,array2)

array([-0.23901099, -0.34707477,  0.30687437,  0.34096855])

# AGGREGATION 

In [109]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
array.sum()

21

In [111]:
array.sum(axis=0)

array([5, 7, 9])

In [112]:
array.sum(axis=1)

array([ 6, 15])

In [113]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
array.mean()

3.5

In [115]:
array.std()

1.707825127659933

In [116]:
array.var()

2.9166666666666665

In [117]:
#array.median(axis=1)

In [118]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [119]:
array.min()

1

In [120]:
array.max()

6

In [121]:
array.argmin()

0

In [122]:
array.argmax()

5

# CONCATENATION

In [123]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

In [124]:
array3 = np.concatenate([array1,array2])

In [125]:
array3
#axis=0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [126]:
np.concatenate([array1,array2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# HSTACK AND VSTACK

In [127]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

In [128]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
array2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [130]:
np.vstack([array1, array2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [131]:
np.hstack([array1, array2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# COLUMN STACKING

In [132]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [133]:
np.column_stack([array1, array2])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [134]:
np.vstack([array1, array2])

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
np.hstack([array1, array2])

array([1, 2, 3, 4, 5, 6])

# SPLITTING

In [136]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [137]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
np.split(array, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [139]:
#np.split(array, 3, axis=1)

# METHODS FOR BOOLEAN ARRAYS

In [140]:
array = np.array([1, 2, 3, 4, 5])

In [141]:
array > 3

array([False, False, False,  True,  True])

In [142]:
(array > 3).sum()

2

In [143]:
(array > 3).any()

True

In [144]:
(array > 3).all()

False

# SORT

In [145]:
array = np.array([5, 2, 3, 1, 4])
array.sort()

In [146]:
array

array([1, 2, 3, 4, 5])

In [147]:
array = np.array([[5, 2, 3],
                  [1, 4, 6]])
print(array)

[[5 2 3]
 [1 4 6]]


In [148]:
array.sort(axis=0)

In [149]:
array

array([[1, 2, 3],
       [5, 4, 6]])

In [150]:
array.sort(axis=1)

In [151]:
array

array([[1, 2, 3],
       [4, 5, 6]])

# ARG SORT

In [152]:
array = np.array([5, 2, 3, 1, 4])
array.argsort()
#The argsort method returns the indices of the sorted array.

array([3, 1, 2, 4, 0], dtype=int64)

# UNIQUE ELEMENTS

In [153]:
array = np.array([1, 1, 2, 2, 3, 3, 4, 4])
np.unique(array)

array([1, 2, 3, 4])

In [154]:
array = np.array([[1, 1], [2, 3]])
np.unique(array)

array([1, 2, 3])

# VECTORIZE METHOD

In [155]:
array = np.array(['1,000', '2,000', '3,000'])

In [156]:
def my_func(x):
    return int(x.replace(',', ''))
remove_commas = np.vectorize(my_func)
remove_commas(array)

array([1000, 2000, 3000])

In [157]:
remove_commas = np.vectorize(lambda x: int(x.replace(',', '')))
remove_commas(array)

array([1000, 2000, 3000])

# FILE INPUT AND OUTPUT

In [158]:
array = np.array([1, 2, 3, 4, 5])
np.save('my_array', array)

In [159]:
np.load('my_array.npy')

array([1, 2, 3, 4, 5])

In [160]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
np.savez('my_arrays.npz', a=array1, b=array2)

In [161]:
archive_array = np.load('my_arrays.npz')
archive_array['a']

array([1, 2, 3, 4, 5])

# LINEAR ALGEBRA 

In [162]:
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])

In [163]:
np.matmul(array1, array2) # or array1 @ array2


array([[19, 22],
       [43, 50]])

In [164]:
np.inner(array1, array2)


array([[17, 23],
       [39, 53]])

In [165]:
np.dot(array1, array2) # or array1.dot(array2)


array([[19, 22],
       [43, 50]])

# SHUFFLE

In [166]:
array = np.arange(10)
np.random.shuffle(array)
array

array([9, 6, 4, 1, 2, 7, 8, 5, 0, 3])

# SEED

In [167]:
np.random.seed(0)

In [168]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [169]:
np.random.rand(5)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [170]:
rng = np.random.RandomState(1234)

In [171]:
rng.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

# DATETIMES AND TIMEDELTAS

In [172]:
np.datetime64('2018-01-01')

numpy.datetime64('2018-01-01')

In [173]:
np.datetime64('2018-01-01 12:00')

numpy.datetime64('2018-01-01T12:00')

In [174]:
np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64')

array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64[D]')

In [175]:
np.arange('2005-02', '2005-03', dtype='datetime64[D]') 

array(['2005-02-01', '2005-02-02', '2005-02-03', '2005-02-04',
       '2005-02-05', '2005-02-06', '2005-02-07', '2005-02-08',
       '2005-02-09', '2005-02-10', '2005-02-11', '2005-02-12',
       '2005-02-13', '2005-02-14', '2005-02-15', '2005-02-16',
       '2005-02-17', '2005-02-18', '2005-02-19', '2005-02-20',
       '2005-02-21', '2005-02-22', '2005-02-23', '2005-02-24',
       '2005-02-25', '2005-02-26', '2005-02-27', '2005-02-28'],
      dtype='datetime64[D]')

In [178]:
np.datetime64('2009-01-01') - np.datetime64('2008-01-01')

numpy.timedelta64(366,'D')

In [179]:
np.timedelta64(1,'W') / np.timedelta64(1,'D')

7.0