In [1]:
import numpy as np

In [2]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(data)

In [3]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2 = arr.reshape(4,2)
arr2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
arr3 = arr.reshape(8, -1)

In [6]:
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [7]:
list = [True, False, True]
arr = np.array(list, dtype=bool)
arr
arr.dtype

dtype('bool')

In [8]:
array = np.array([{"name": "John", "age": 25}, [1, 2, 3], "hello"], dtype=object)
array

array([{'name': 'John', 'age': 25}, list([1, 2, 3]), 'hello'],
      dtype=object)

In [9]:
np.eye(3, k=1) 

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
print(array[0, 0])

1


In [12]:
print(array[[0, 1], [1, 0]])

[2 3]


In [13]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array[0:5]
array[:5]

array([1, 2, 3, 4, 5])

In [14]:
array[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
array[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array[:5:2]

array([1, 3, 5])

In [17]:
array[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
array = np.arange(10)
arr_slice = array[5:8].copy()
print(arr_slice)

[5 6 7]


In [19]:
arr_slice[:] = 752
print(arr_slice)

[752 752 752]


In [20]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)


In [22]:
data

array([[-1.78754485,  0.06928508,  0.42629788,  0.76499239],
       [ 0.53444979,  1.20631472, -0.37750499, -0.66735276],
       [-0.12876067,  0.04201912, -0.48595125, -0.82523574],
       [-1.90937534,  0.85197715, -0.38023788,  0.07990321],
       [ 0.4474706 , -0.22238918,  0.83084148, -1.10860695],
       [ 0.51357458, -0.59320405,  0.07621963, -2.50912022],
       [ 1.68566706,  0.10293901,  0.06236028, -0.49565715]])

In [23]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [24]:
data[names == "Bob"]

array([[-1.78754485,  0.06928508,  0.42629788,  0.76499239],
       [-1.90937534,  0.85197715, -0.38023788,  0.07990321]])

In [25]:
data< -0.5

array([[ True, False, False, False],
       [False, False, False,  True],
       [False, False, False,  True],
       [ True, False, False, False],
       [False, False, False,  True],
       [False,  True, False,  True],
       [False, False, False, False]])

In [26]:
data[data < -0.5] = 0

In [27]:
array = np.array(['1,000', '2,000', '3,000'])
array

array(['1,000', '2,000', '3,000'], dtype='<U5')

In [28]:
def my_func(x):
    return int(x.replace(',', ''))
remove_commas = np.vectorize(my_func)
remove_commas(array)

array([1000, 2000, 3000])

In [29]:
np.random.rand(5)

array([0.32735668, 0.83046404, 0.44699615, 0.34383206, 0.68018059])

In [33]:
np.random.seed(234254254)
np.random.rand(5)

array([0.23555743, 0.50498221, 0.12783246, 0.96601977, 0.88487684])

In [31]:
np.random.rand(5)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [32]:
rng = np.random.RandomState(1234)
rng.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [46]:
import pandas as pd
area = pd.Series({'Rotterdam': 41.4, 'Utrecht': 30.5, 'Amsterdam': 219.3, 'Eindhoven': 30.5, 'The Hague': 31.4})

In [47]:
area

Rotterdam     41.4
Utrecht       30.5
Amsterdam    219.3
Eindhoven     30.5
The Hague     31.4
dtype: float64

In [48]:
area.sort_values(ascending=False, inplace=True).sort_index()

In [49]:
area

Amsterdam    219.3
Rotterdam     41.4
The Hague     31.4
Utrecht       30.5
Eindhoven     30.5
dtype: float64

In [57]:
data = {'Name': ['Valheim', 'Among Us', 'Minecraft', 'Fortnite', 'Genshin Impact'],
        'Year': [2021, 2018, 2011, 2017, 2020],
        'Genre': ['Survival', 'Social Deduction', 'Sandbox', 'Battle Royale', 'Action RPG'],
        'Developer': ['Iron Gate Studio', 'InnerSloth', 'Mojang', 'Epic Games', 'miHoYo'],
        'Price': [19.99, 4.99, 26.95, 0.00, 0.00]}

df = pd.DataFrame(data)
df

Name  Year             Genre         Developer  Price
0         Valheim  2021          Survival  Iron Gate Studio  19.99
1        Among Us  2018  Social Deduction        InnerSloth   4.99
2       Minecraft  2011           Sandbox            Mojang  26.95
3        Fortnite  2017     Battle Royale        Epic Games   0.00
4  Genshin Impact  2020        Action RPG            miHoYo   0.00

In [53]:
df.set_index("Name", inplace=True)

In [54]:
df

Year             Genre         Developer  Price
Name                                                           
Valheim         2021          Survival  Iron Gate Studio  19.99
Among Us        2018  Social Deduction        InnerSloth   4.99
Minecraft       2011           Sandbox            Mojang  26.95
Fortnite        2017     Battle Royale        Epic Games   0.00
Genshin Impact  2020        Action RPG            miHoYo   0.00

In [59]:
df.reset_index(drop=True)

Name  Year             Genre         Developer  Price
0         Valheim  2021          Survival  Iron Gate Studio  19.99
1        Among Us  2018  Social Deduction        InnerSloth   4.99
2       Minecraft  2011           Sandbox            Mojang  26.95
3        Fortnite  2017     Battle Royale        Epic Games   0.00
4  Genshin Impact  2020        Action RPG            miHoYo   0.00

In [68]:
series = pd.Series(df["Name"])
series

0           Valheim
1          Among Us
2         Minecraft
3          Fortnite
4    Genshin Impact
Name: Name, dtype: object

In [69]:
series.index = df["Year"].to_list()

In [70]:
series

2021           Valheim
2018          Among Us
2011         Minecraft
2017          Fortnite
2020    Genshin Impact
Name: Name, dtype: object

In [71]:
series.sort_values()

2018          Among Us
2017          Fortnite
2020    Genshin Impact
2011         Minecraft
2021           Valheim
Name: Name, dtype: object

In [72]:
series.sort_index()

2011         Minecraft
2017          Fortnite
2018          Among Us
2020    Genshin Impact
2021           Valheim
Name: Name, dtype: object

In [73]:
df2 = pd.DataFrame(series)
df2

Name
2021         Valheim
2018        Among Us
2011       Minecraft
2017        Fortnite
2020  Genshin Impact

In [74]:
df2.reset_index(inplace=True)
df2

index            Name
0   2021         Valheim
1   2018        Among Us
2   2011       Minecraft
3   2017        Fortnite
4   2020  Genshin Impact

In [75]:
df2.rename(columns={"index": "Year"}, inplace=True)
df2

Year            Name
0  2021         Valheim
1  2018        Among Us
2  2011       Minecraft
3  2017        Fortnite
4  2020  Genshin Impact

In [76]:
df2.sort_values(by=["Name", "Year"], ascending=[True, False], inplace=True)
df2

Year            Name
1  2018        Among Us
3  2017        Fortnite
4  2020  Genshin Impact
2  2011       Minecraft
0  2021         Valheim

In [ ]:
series = df2["Name"]

In [89]:
df1 = pd.DataFrame([[1, 2], [4, 5], [7, 8]], index=['a', 'b', 'c'], columns=['col1', 'col2'])
df1

col1  col2
a     1     2
b     4     5
c     7     8

In [90]:
df1.iloc[0]

col1    1
col2    2
Name: a, dtype: int64

In [91]:
df1.iloc[1:2]

col1  col2
b     4     5

In [93]:
df1.loc['a':'b']

col1  col2
a     1     2
b     4     5

In [ ]:
df1.loc[[2, 3], 'col2']

In [98]:
df2 = pd.DataFrame({'col1': [1, 1,1,  2, 2, 3, 3, 4, 4],
                    'col2': [1, 1,2, 2, 2, 3, 3, 4, 4]})
df2

col1  col2
0     1     1
1     1     1
2     1     2
3     2     2
4     2     2
5     3     3
6     3     3
7     4     4
8     4     4

In [100]:
df2.drop_duplicates(keep='first', subset=["col1" ])

col1  col2
0     1     1
3     2     2
5     3     3
7     4     4

In [101]:
df4 = pd.DataFrame({'col1': ['2019-08-02', '2020-09-25', '2023-01-03'],
                    'col2': ['2021-12-01 12:00:00', '2020-05-21 04:30:00', '2023-02-04 12:40:00']})
df4

col1                 col2
0  2019-08-02  2021-12-01 12:00:00
1  2020-09-25  2020-05-21 04:30:00
2  2023-01-03  2023-02-04 12:40:00

In [102]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    3 non-null      object
 1   col2    3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes


In [103]:
df4['col1'] = pd.to_datetime(df4['col1'])
df4['col2'] = pd.to_datetime(df4['col2'])

In [104]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   col1    3 non-null      datetime64[ns]
 1   col2    3 non-null      datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 180.0 bytes


In [106]:
df4['col2'].dt.month

0    12
1     5
2     2
Name: col2, dtype: int32

In [107]:
df4

col1                col2
0 2019-08-02 2021-12-01 12:00:00
1 2020-09-25 2020-05-21 04:30:00
2 2023-01-03 2023-02-04 12:40:00

In [112]:
df4['col2'].dt.strftime('%Y---%m--%d')

0    2021---12--01
1    2020---05--21
2    2023---02--04
Name: col2, dtype: object

In [111]:
df4['col2'] + pd.Timedelta(days=-1)

0   2021-11-30 12:00:00
1   2020-05-20 04:30:00
2   2023-02-03 12:40:00
Name: col2, dtype: datetime64[ns]

In [114]:
imdb = pd.read_csv('https://parsa-abbasi.github.io/slides/pandas/imdb_top_250_movies.csv', index_col='rank')
imdb.head(5)

name  year  rating               genre certificate  \
rank                                                                           
1     The Shawshank Redemption  1994     9.3               Drama           R   
2                The Godfather  1972     9.2         Crime,Drama           R   
3              The Dark Knight  2008     9.0  Action,Crime,Drama       PG-13   
4        The Godfather Part II  1974     9.0         Crime,Drama           R   
5                 12 Angry Men  1957     9.0         Crime,Drama    Approved   

     run_time                                            tagline     budget  \
rank                                                                          
1      2h 22m  Fear can hold you prisoner. Hope can set you f...   25000000   
2      2h 55m                         An offer you can't refuse.    6000000   
3      2h 32m                                    Why So Serious?  185000000   
4      3h 22m       All the power on earth can't change destiny.   13000000   
5      1h 36m  Life Is In Their Hands -- Death Is On Their Mi...     350000   

      box_office                                              casts  \
rank                                                                  
1       28884504  Tim Robbins,Morgan Freeman,Bob Gunton,William ...   
2      250341816  Marlon Brando,Al Pacino,James Caan,Diane Keato...   
3     1006234167  Christian Bale,Heath Ledger,Aaron Eckhart,Mich...   
4       47961919  Al Pacino,Robert De Niro,Robert Duvall,Diane K...   
5            955  Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...   

                 directors                                          writers  
rank                                                                         
1           Frank Darabont                      Stephen King,Frank Darabont  
2     Francis Ford Coppola                  Mario Puzo,Francis Ford Coppola  
3        Christopher Nolan  Jonathan Nolan,Christopher Nolan,David S. Goyer  
4     Francis Ford Coppola                  Francis Ford Coppola,Mario Puzo  
5             Sidney Lumet                                    Reginald Rose

In [119]:
imdb.groupby("year").count().loc[:, "rating"]

year
1921    1
1924    1
1925    1
1926    1
1927    1
       ..
2018    4
2019    6
2020    2
2021    2
2022    1
Name: rating, Length: 86, dtype: int64

In [121]:
imdb.groupby(["year", "genre"])['rating'].mean()

year  genre                   
1921  Comedy,Drama,Family         8.3
1924  Action,Comedy,Romance       8.2
1925  Adventure,Comedy,Drama      8.1
1926  Action,Adventure,Comedy     8.1
1927  Drama,Sci-Fi                8.3
                                 ... 
2020  Biography,Drama,History     8.4
      Drama,Mystery               8.2
2021  Action,Adventure,Fantasy    8.2
      Crime,Drama,Mystery         8.8
2022  Action,Drama                8.3
Name: rating, Length: 245, dtype: float64

In [122]:
df1 = pd.DataFrame({'City': ['Amsterdam', 'Tilburg', 'Rotterdam', 'Utrecht'],
                    'Population': [821752, 213310, 623652, 340852]})
df2 = pd.DataFrame({'City': ['Rotterdam', 'Nijmegen', 'Eindhoven', 'Tilburg', 'Utrecht'],
                    'Area': [41.78, 32.61, 213.31, 37.29, 30.93]})

In [123]:
df1

City  Population
0  Amsterdam      821752
1    Tilburg      213310
2  Rotterdam      623652
3    Utrecht      340852

In [124]:
df2

City    Area
0  Rotterdam   41.78
1   Nijmegen   32.61
2  Eindhoven  213.31
3    Tilburg   37.29
4    Utrecht   30.93

In [131]:
pd.merge(left=df1,
          right=df2,
            how='cross',)

City_x  Population     City_y    Area
0   Amsterdam      821752  Rotterdam   41.78
1   Amsterdam      821752   Nijmegen   32.61
2   Amsterdam      821752  Eindhoven  213.31
3   Amsterdam      821752    Tilburg   37.29
4   Amsterdam      821752    Utrecht   30.93
5     Tilburg      213310  Rotterdam   41.78
6     Tilburg      213310   Nijmegen   32.61
7     Tilburg      213310  Eindhoven  213.31
8     Tilburg      213310    Tilburg   37.29
9     Tilburg      213310    Utrecht   30.93
10  Rotterdam      623652  Rotterdam   41.78
11  Rotterdam      623652   Nijmegen   32.61
12  Rotterdam      623652  Eindhoven  213.31
13  Rotterdam      623652    Tilburg   37.29
14  Rotterdam      623652    Utrecht   30.93
15    Utrecht      340852  Rotterdam   41.78
16    Utrecht      340852   Nijmegen   32.61
17    Utrecht      340852  Eindhoven  213.31
18    Utrecht      340852    Tilburg   37.29
19    Utrecht      340852    Utrecht   30.93

In [132]:
df1 = pd.DataFrame({'City': ['Amsterdam', 'Tilburg', 'Rotterdam', 'Utrecht'],
                    'Population': [821752, 213310, 623652, 340852]})
df2 = pd.DataFrame({'City': ['Eindhoven', 'Nijmegen', 'Groningen'],
                    'Population': [223452, 165432, 248563]})


In [133]:
df1

City  Population
0  Amsterdam      821752
1    Tilburg      213310
2  Rotterdam      623652
3    Utrecht      340852

In [134]:
df2

City  Population
0  Eindhoven      223452
1   Nijmegen      165432
2  Groningen      248563

In [135]:
df3 = pd.concat([df1, df2])

In [136]:
df3

City  Population
0  Amsterdam      821752
1    Tilburg      213310
2  Rotterdam      623652
3    Utrecht      340852
0  Eindhoven      223452
1   Nijmegen      165432
2  Groningen      248563

In [137]:
df = pd.DataFrame({'Population': [821752, 213310, 623652, 340852, 223452, 165432, 248563],
                   'Area': [41.78, 32.61, 213.31, 37.29, 30.93, 32.61, 213.31],
                   'Density': [19857, 6554, 2954, 9123, 10000, 6554, 2954]}) 

In [138]:
df

Population    Area  Density
0      821752   41.78    19857
1      213310   32.61     6554
2      623652  213.31     2954
3      340852   37.29     9123
4      223452   30.93    10000
5      165432   32.61     6554
6      248563  213.31     2954

In [139]:
df.corr()

Population      Area   Density
Population    1.000000  0.197199  0.564658
Area          0.197199  1.000000 -0.602733
Density       0.564658 -0.602733  1.000000